beatrix/urls.py
from django.urls import path
from . import views
from beatrix.views import( 
AanmeldView,
FlexeventsView,
ResultsView,
activiteit,
activityPage,
apiOverview, 
createRoom, deleteMessage, deleteRoom,
directvote,
erv_SchemaPage,
erv_activityPage,
erv_createRoom,
erv_deleteMessage,
erv_deleteRoom,
erv_home,
erv_loginPage,
erv_room,
erv_topicsPage,
erv_updateRoom,
erv_updateUser,
erv_userProfile,
events,
flexeventbeheer, 
home,
loginPage, logoutUser,
personenlijst,
recurrent_event,
registerPage, room, 
topicsPage, updateRoom, updateUser, userProfile,
vote, 
erv_recurrentRoom,
DetailView,
aantalregels,
# vote2,
)

urlpatterns = [
    path('', erv_home, name='erv-home'),
    path('beatrix', erv_home, name='erv-home'),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('topics/', topicsPage, name="topics"),
    path('update-user/', updateUser, name="update-user"),
    path('register/', registerPage, name="register"),    
    path('profile/<str:pk>/', userProfile, name='user-profile'),
    path('create-room/', createRoom, name='create-room'),
    path('update-room/<str:pk>/', updateRoom, name='update-room'),
    path('delete-room/<str:pk>/', deleteRoom, name='delete-room'),
    path('delete-message/<str:pk>/', deleteMessage, name='delete-message'),
    path('activity/', activityPage, name="activity"),

    path('erv-create-flex/', erv_createRoom, name='erv-create-flex'),
    path('erv-update-flex/<str:pk>/', erv_updateRoom, name='erv-update-flex'),
    path('erv_activity/', erv_home, name="erv-activity"),
    path('erv-room/<str:pk>/', erv_room, name='erv-room'),    
    path('erv-topics/', erv_topicsPage, name="erv-topics"),
    path('erv-delete-room/<str:pk>/', erv_deleteRoom, name='erv-delete-room'),
    path('erv-profile/<str:pk>/', erv_userProfile, name='erv-user-profile'),
    path('erv-update-room/<str:pk>/', erv_updateRoom, name='erv-update-room'),
    path('erv-delete-message/<str:pk>/', erv_deleteMessage, name='erv-delete-message'),
    path('erv-login/', erv_loginPage, name="erv-login"),
    path('erv-logout/', logoutUser, name="erv-logout"),
    path('erv-register/', registerPage, name="erv-register"),    
    path('erv-update-user/', erv_updateUser, name="erv-update-user"),

    path('recurrent/', recurrent_event, name='recurrent'),
    path('erv-recurrency/<str:pk>', erv_recurrentRoom, name='erv-recurrency'),
    path('<int:event_id>/aanmelden/',vote, name='vote'),  
    path('<int:event_id>/directaanmelden/',directvote, name='directvote'),  
    # path('<str:event_id>/<str:usr>/aanmelden/',vote2, name='vote2'),  
    path('flexevents/', erv_SchemaPage, name="aanmelden"),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('api/person/', personenlijst,name='api-person'),    
    path('api/', apiOverview,name='api-overview'),    
    path('api/aantalregels/', aantalregels,name='api-aantalregels'),    
    path('flexevent/<str:pk>/', activiteit,name='flexevent'),    
    path('flexeventbeheer', flexeventbeheer,name='flexeventbeheer'),    
    path('topic-list/', views.topicList,name='topic-list'),    
    path('event-create/', views.eventCreate,name='event-create'),    
    path('event-list/', views.eventList,name='event-list'),    
    path('event-list/<str:pk>/delete/', views.eventDelete, name="event-delete"),
    path('event-list/<str:pk>/', views.getNote, name="event"),
    path('notes/<str:pk>/', views.getNote, name="note"),
    path('event-list/<str:find>/find/', views.findNote, name="find-note"),
    path('notes/', views.getNotes, name="notes"),
    path('notes/create/', views.createNote, name="create-note"),
    path('notes/<str:pk>/update/', views.updateNote, name="update-note"),
    path('notes/<str:pk>/delete/', views.deleteNote, name="delete-note"),
    ]
# https://docs.djangoproject.com/en/3.1/topics/http/urls/

deelnamehelper/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beatrix.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

beatrix/models.py
from datetime import datetime
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
SCULL = [
            ('--', '--'),
            ('sc1', 'sc1'),
            ('sc2', 'sc2'),
            ('sc2a', 'sc2a'),
            ('sc3', 'sc3'),
            ('sc4', 'sc4'),
            ('b1', 'b1'),
            ('b2', 'b2'),
            ('b3', 'b3'),
            ('b4', 'b4'),
            ('st1', 'st1'),
            ('st2', 'st2'),
            ('st3', 'st3'),
]
DVDW = [
            ('--', '--'),
            ('0', 'maandag'),
            ('1', 'ma-wo'),
            ('0,3,4', 'ma-wo-vr'),
]
TIJDBLOK = [
            ('--', '--'),
            ('1','09:00'),
            ('2','13:00'),
            ('3','17:30'),
]

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True) # database field (can Empty), form field (can Empty)
    participants = models.ManyToManyField(User, related_name='participant', blank=True)
    updated = models.DateTimeField(auto_now=True) # everytime save (or updated) the field
    created = models.DateTimeField(auto_now_add=True) # first time created the field

    class Meta:
        ordering = ['-updated', '-created'] # ('-' for reverse the order)

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE) # when room delete, delete all chiled messages
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)     

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    name = models.CharField(max_length=100)
    avatar=models.ImageField(null=True,default="avatar.svg")      # install Pillow is needed
    email = models.CharField(max_length=100,blank=True)
    is_flex = models.BooleanField(default=True)        #wil ingedeeld worden in flexpoule
    is_host = models.BooleanField(default=False)        #kan flexhost zijn
    keuzes = models.IntegerField(default=0) #aantal keren als host gekozen
    roeileeftijd = models.CharField(max_length=20,blank=True)
    is_lid= models.BooleanField(default=True)           #is roeiend lid;member
    in_poule = models.BooleanField(default=False)       #wil flexibel roeiern
    vaart = models.BooleanField(default=False)          #zit in ingedeelde boot op het water
    pos1 = models.CharField(max_length=18, choices=SCULL,default='sc1')  #aanbod vaardigheid om voorstel te berekenen voor wat nodig is aan in te delen boten
    pos2 = models.CharField(max_length=18, choices=SCULL,default='sc1') 
    pos3 = models.CharField(max_length=18, choices=SCULL,default='sc1') 
    pos4 = models.CharField(max_length=18, choices=SCULL,default='sc1') 
    pos5 = models.CharField(max_length=318, choices=SCULL,default='st1') 
    coach = models.CharField(max_length=18, choices=SCULL,default='st1')     
    keuzes = models.IntegerField(default=0) #aantal keren als host gekozen

    def __str__(self):
        return self.name

class Flexevent(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # host = models.ManyToManyField(User,through='Hosts')  ##, on_delete=models.SET_NULL, null=True)
    id = models.AutoField(primary_key=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,null=True) ##SET_NULL, null=True)
    event_text = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True) # database field (can Empty), form field (can Empty)
    pub_date = models.CharField(max_length=35)
    datum = models.DateField(auto_now=False)
    pub_time = models.CharField(max_length=35, default='10:00')
    lid = models.ManyToManyField(User, related_name='deelnemer', blank=True)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

class Flexlid(models.Model):
    flexevent = models.ForeignKey(Flexevent, on_delete=models.CASCADE,null=True)
    member = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    is_host = models.BooleanField(default=False)

    class Meta:
        ordering = ('member',)    
    def __str__(self):
        return "%s" % (self.flexevent)        


class Bericht(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Flexevent, on_delete=models.CASCADE) # when room delete, delete all chiled messages
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)     

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

# python .\manage.py makemigrations
# python .\manage.py migrate
class Flexrecurrent(models.Model):
    regels = models.CharField(max_length=18,default='30')

class Recurrent(models.Model):
    name = models.CharField(max_length=18,default='FlexibelRoeien')
    start=models.CharField(max_length=18,default='30')
    end=models.CharField(max_length=18,default='30')
    trainingsweken=models.CharField(max_length=18,default='4')
    onderwerp=models.CharField(max_length=18,default='flexroeien')
    dagvandeweek = models.CharField(max_length=18, choices=DVDW,default='0') 
    blok = models.CharField(max_length=18, choices=TIJDBLOK,default='1') 
    verwijder_oude_flexevents=models.BooleanField(default=True)
    resetsequence=models.BooleanField(default=True)
    verwijder_oude_onderwerpen=models.BooleanField(default=False)
    
    def __str__(self):
        return self.name



class Instromer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Note(models.Model):
    body = models.TextField(null=True, blank=True)
    host = models.CharField(max_length=200,default='wb')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

beatrix/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Flexevent, Room,User,Recurrent


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = '__all__'
    #   fields = ['name', 'username', 'email', 'password1', 'password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

class erv_RoomForm(ModelForm):
    class Meta:
        model = Flexevent
        fields = '__all__'
        exclude = ['host', 'lid']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        fields = ['username', 'email']        
        # fields = ['avatar', 'name', 'username', 'email', 'bio']        

class RecurrentForm(ModelForm):
    class Meta:
        model = Recurrent
        fields = '__all__'
        exclude = ['start', 'end']

beatrix/templates/beatrix/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} geleden</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>verwijder</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <p>reacties op: “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>

beatrix/templates/beatrix/delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    <input type="submit" value="Confirm" />
</form>

{% endblock content %}

beatrix/templates/beatrix/erv-detail.html
{% extends 'erv-base.html' %}
{% block content %}
<main class="layout layout--3">
  {% comment %} 5 okt 2022 {% endcomment %}
  <div class="container">
    
    <form action="{% url 'vote' event.id %}" method="post">
      {% csrf_token %}
      <div class="phone">
        <div class="phone-mirror">
        <li><a href="/" class="btn btn-warning btn-sm">Home</a></li>
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>Terug</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>
            FlexEvent {{event.datum|date:"d M Y"}} --{{event.name}}
          </h3>
        </div>

        <table class="datum-table">
          <thead>
            <hr>
            <tr>
              <th>Reeds aangemeld:</th>
              <th><input type="submit" value="Meld Af "> </th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for aa in aanwezig %}
            <tr>

            <td>{{t.id }}</td>
            <td>{{aa.id}} {{aa.person.pos1}} {{aa.last_name}} </td>
               <!-- {{aa.person.pos2}} {{aa.person.pos3}} {{aa.person.pos4}} {{aa.person.pos5}}</td> -->
            <td>
              <input type="checkbox" name="afmelding" id="host{{ forloop.counter }}" value="{{ aa.id }}">
            </td>
            <td> </td>
            <!-- <td>
              <input type="checkbox" name="hoofdhost" id="host{{ forloop.counter }}" value="{{ aa.id }}">
            </td> -->
            </td>

            {% endfor %}
            </tr>
          </tbody>
        </table>
        <table class='person-table'>
          <thead>
            <hr>
            <tr>
              <th> <input id="search-input" name="zoeknaam" class="form-control" type="text" placeholder='@vind kandidaat'></th>
              <th><input type="submit" value="Meld Aan"> </th>
              <th>Totaal ( {{users.count}}) </th>
                 <!-- voor {{event.datum|date:"d M Y"}}</th> -->
          </thead>
          </tr>

          <tbody id=aanmeldingen>
            <td>{% for t in users %}
            </td>
            <tr>
              
              <td>{{t.user}}{{t.username}}</td>

              <td>  {{t.person.pos1}} </td>
                 <!-- {{t.person.pos2}} {{t.person.pos3}} {{t.person.pos4}} {{t.person.pos5}}</td> -->
              <td> <input type="checkbox" name="aanmelding" id="host{{ 2 }}" value="{{ t.user_id }}"> </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
        </div>
        </div>
        </div>
        {# {{users.count}} #}
</form>
</div>
</div>
</div>
</main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script id="aantalregels" type="application/json">{{aantalregels}}</script>
<script>


$('#search-input').on('keyup',function(){
    var value = $(this).val()
    console.log('Value:', value)
     var data = searchTable(value,myArray)
     console.log(data)
    buildTable(data)
})

$.ajax({
    method:'GET',
    url:'http://127.0.0.1:8000/api/person/',
    success:function(response){
        myArray = response
        buildTable(myArray)
        console.log(myArray)
    }
})

function searchTable(value, data){
    var filteredData =[]
    for (var i = 0; i < data.length; i++){
        value=value.toLowerCase()
        var name = data[i].name.toLowerCase()
        if (name.includes(value)){
            filteredData.push(data[i])
        }
    }
    return filteredData
}

function buildTable(data){
  const regels = JSON.parse(document.getElementById('aantalregels').textContent);
 console.log(regels)
  var table = document.getElementById('aanmeldingen')
table.innerHTML=``
for (var i = 0; i <= regels;i++){
      var row = `<tr> 
    <td> ${data[i].user} </td> 
    <td> ${data[i].name} </td> 
    <td> <input type="checkbox" name="aanmelding" id="host{{ forloop.counter }}" value="${data[i].user}"> </td>
    <td> ${data[i].pos1} </td> 
    </tr>`
  table.innerHTML += row
}
}
  
</script>
{% endblock %}

beatrix/templates/beatrix/erv-feed_component_old.html
{% for room in rooster %}
<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a href="{% url 'results' room.id %}" class="roomListRoom__author">
      <div class="avatar avatar--small">
        <img src="{{room.host.avatar.url}}" />
      </div>
      <span>@{{room.flexhost}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{room.created|timesince}} geleden</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    <a href="{% url 'room' room.id %}">{{room.name}}</a>
  </div>
  <div class="roomListRoom__meta">
    <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} In de boot
    </a>
    <p class="roomListRoom__topic">{{room.topic.name}}</p>
  </div>
</div>
{% endfor %}

beatrix/templates/beatrix/erv-login_register.html
{% extends 'erv-base.html' %} {% block content %}
<main class="auth layout">
  {% if page == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <div class="form__action">
            <a class="btn btn--dark" href="/"
              >Cancel</a
            >

          </div>

          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Flexibel roeien</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %} {{form.as_p}}
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="bijvoorbeeld: info@beatrix.nl"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Nog niet geregistreerd?</p>
          <a href="{% url 'erv-register' %}" class="btn btn--link"
            >Registreer</a
          >
        </div>
      </div>
    </div>
  </div>
  {% else %}

  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}"
              >Cancel</a
            >

          </div>

          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Uw gebruikers naam</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %} {{form.as_p}}

          <input type="submit" value="Register" />
        </form>

        <div class="auth__action">
          <p>Already signed up yet?</p>
          <a href="{% url 'erv-login' %}" class="btn btn--link">Login</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock content %}

beatrix/templates/beatrix/person_list.html
{% extends 'base.html' %}
{% block content %}
<form>
{% csrf_token %}
{% load static %}
<div class="mobile">
<div class="phone">
<div class="phone-mirror">
<table class="beatrix-table">
  <thead>
    <tr>
      <th> <a href="/" class="fa fa-home fa-3x" ></a></th>
      {% comment %} <th> <a href="{% url 'person:aanmelden' %}" class="btn btn-warning btn-sm" >Aanmelden</a></th> {% endcomment %}
      {% comment %} <th><a href="{% url 'beatrix:rooster' %}" class="fa fa-list fa-3x"  ></a></th> {% endcomment %}
      {% comment %} <th><a href="{% url 'beatrix:hoofdhost' %}" class="fa fa-user fa-3x"  ></a></th> {% endcomment %}
    </tr>
  </thead>
  <tbody>
    <tr>
    </tr>
  </tbody>
</table>
         <table class="beatrix-table">
              <thead>
                <tr>
                  <th>Maand</th>
                  <th>Host</th>
                </tr>
              </thead>
                   <tbody>
                     {% for h in rooster %}
                     <tr class="active-row">
                    <td> {{h.pub_date}} </td>
                    <td> {{h.flexhost}} </td>
                             {% comment %} <td><a href="{% url 'ploeg:kal' h.pub_date %}">maand {{h.pub_date}}</a></td>  {% endcomment %}
                             {% endfor %}   
                         </tr>
                      </tbody>
     </table>
</div>
</div>
</div>
</form>
{% endblock  %}

beatrix/templates/beatrix/topics.html
{% extends 'main.html' %}

{% block content %}

    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Bekijk Mogelijkheden</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form action ="" method = "GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Zoek Mogelijkheid in More" />
              </label>
            </form>

            <ul class="topics__list">
            <li>
                <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}} </span></a>
                </li>
            {% for topic in topics %}
              <li>
                <a href="{%url 'home' %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.count}} </span></a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}